<?xml version="1.0"?>
<robot name="chair" xmlns:xacro="http://wiki.ros.org/xacro">

    <xacro:macro name="simple_chair"
                params="prefix='chair_' connected_to:='' xyz:='0 0 0' rpy:='0 0 0' height:=1.0 x_size:=0.5 y_size=0.5
                thickness=0.02 mass=3.0">

        <material name="violet">
            <color rgba="0.0 0.0 0.4 0.6"/>
        </material>

        <xacro:if value="${connected_to == ''}">
        <link name="world"/>
        <xacro:property name="base_frame_name" value="world"/>
        </xacro:if>
        <xacro:unless value="${connected_to == ''}">
        <xacro:property name="base_frame_name" value="${connected_to}"/>
        </xacro:unless>
        <xacro:if value="${connected_to == 'odom'}">
        <link name="odom"/>
        <xacro:property name="base_frame_name" value="odom"/>
        </xacro:if>

        <joint name="${prefix}base_to_${base_frame_name}" type="fixed">
        <parent link="${base_frame_name}"/>
        <child link="${prefix}base_link"/>
        <origin rpy="${rpy}" xyz="${xyz}"/>
        </joint>

        <link name="${prefix}base_link"/>
        <joint name="base_to_bottom" type="fixed">
        <parent link="${prefix}base_link"/>
        <origin xyz="0 0 ${height/2}"/>
        <child link="${prefix}bottom_link"/>
        </joint>

        <link name="${prefix}bottom_link">
        <visual>
            <origin xyz="0 0 0"/>
            <geometry>
            <box size="${x_size} ${y_size} ${height}"/>
            </geometry>
            <material name="violet"/>
        </visual>
        <collision>
            <origin xyz="0 0 0"/>
            <geometry>
            <box size="${x_size} ${y_size} ${height}"/>
            </geometry>
        </collision>
        </link>
    
    </xacro:macro>

</robot>